### ISSUE TITLE
DSL and space sensitivity

### ISSUE THREAD

**Issue by NerdFan** [MrTheSoulz/NerdPack#44]
Hi,

looks like there is huge mess with space removal ATM.
For example:
   { 'Flame Shock', {
      'target.debuff(Flame Shock)',
      'target.debuff(Flame Shock).duration <= 2',
   } },

last condition passes space removal:
before: target.debuff(Flame Shock).duration <= 2
after: target.debuff.duration<=2(Flame Shock)

and comparizion does not work properly anymore...

**Comment by MrTheSoulz** [comment]
it should look like: target.debuff.duration<=2(Flame Shock)
the arguments dont need to be in a specific place, pString will remove it again and process it no matter where it is in the string as long as it is inside the parentheses.
Ive sent some tweaks for comparison, could you re-test and give me feedback?

**Comment by MrTheSoulz** [comment]
Ok, should be fixed in: https://github.com/MrTheSoulz/NerdPack/commit/e67170ce8c8a389455c4cee3ffccb147b6a5c9fb

I found a better way to approch this once i revisoted the problem, thanks for reporting!

**Comment by MrTheSoulz** [comment]
Re-open this issues if needed.

**Comment by NerdFan** [comment]
Hi,

there is something wrong still because code example above do not work anymore, it fails at this point:
'target.debuff(Flame Shock).duration <= 2',
and stays to spam Flame Shock even if debuff duration is >2.

There is another example:
RegisterConditon("log", function(args)
   print( 'Log : '..' - '..(args or 'nil') )
   return true
end)
Called { 'Spell', 'log(1)' },

'old' version printed: Log: - 1
'new' version does: Log: - nil

After improvements it prints: Log : nil - 1
RegisterConditon("log", function(args, args2)
   print( 'Log : '..' - '..(args or 'nil')..' - '..(args2 or 'nil') )
   return true
end)

For conclusion: there is some messup with parameters and conditions after latest changes!

**Comment by MrTheSoulz** [comment]
Ok, i think ive fixed now...
If i did, close this isse :)

**Comment by NerdFan** [comment]
Hi,

In syntax wise I'd like your previous code more ;-)

At first it did not fix additional parameter issue give as exmaple about log(1). It looks like minor issue but I expect that it will break many "home made" condidions that are not realated with spell nor target.

2nd: now it  is a bit better but another realted issue found. For example this code will fail on case if there is 0 charges. Most probably comparision "=" will not work properly at all as there is executed 0=0 and that is not comparision.
      { 'Stormkeeper', {
         'player.buff(Storm Totem)',
         'player.spell(Lava Burst).charges = 0',
      } },
Current workaround is here:
      { 'Stormkeeper', {
         'player.buff(Storm Totem)',
         'player.spell(Lava Burst).charges == 0',
      } },
Stack trace:
```
Message: Interface\AddOns\NerdPack\system\dsl.lua:37: attempt to call a nil value
Time: 09/13/16 12:43:36
Count: 1
Stack: Interface\AddOns\NerdPack\system\dsl.lua:37: in function <Interface\AddOns\NerdPack\system\dsl.lua:27>
Interface\AddOns\NerdPack\system\dsl.lua:50: in function <Interface\AddOns\NerdPack\system\dsl.lua:42>
(tail call): ?
(tail call): ?
Interface\AddOns\NerdPack\system\dsl.lua:70: in function <Interface\AddOns\NerdPack\system\dsl.lua:64>
(tail call): ?
Interface\AddOns\NerdPack\system\engine.lua:362: in function `Parse'
Interface\AddOns\NerdPack\system\engine.lua:342: in function `Parse'
Interface\AddOns\NerdPack\system\engine.lua:342: in function `Parse'
Interface\AddOns\NerdPack\system\engine.lua:342: in function `Parse'
Interface\AddOns\NerdPack\system\engine.lua:385: in function `callback'
Interface\AddOns\NerdPack\system\timer.lua:12: in function <Interface\AddOns\NerdPack\system\timer.lua:8>
Interface\SharedXML\C_TimerAugment.lua:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals: mString = "player.spell(Lava Burst).charges = 0"
spell = "Stormkeeper"
(for index) = 8
(for limit) = 8
(for step) = 1
i = 8
Comperator = "="
tempT = <table> {
 1 = 0
 2 = 0
}
(*temporary) = nil
(*temporary) = "attempt to call a nil value"
tableComparator = <table> {
 1 = ">="
 2 = "<="
 3 = "!="
 4 = "~="
 5 = "=="
 6 = ">"
 7 = "<"
 8 = "="
}
pString = <function> defined @Interface\AddOns\NerdPack\system\dsl.lua:7
```

**Comment by NerdFan** [comment]
Sorry, closed by mistake

**Comment by MrTheSoulz** [comment]
Right, seems lile i need a sanity check for nils.
About #=#,  it wont work with the way i build the comparatores. Crs are gonna need to change to ==, same for !=, it becomes ~=.

**Comment by MrTheSoulz** [comment]
Ok, think ive fixed the nil issues and managed to support "!=" & "=" again.
Currently testing the log(1) issue

**Comment by MrTheSoulz** [comment]
Log(1) seems to work as intended.
Note: arg is target and arg2 is stuff inside parenthesis.
This applys too all conditions unlike the old dsl.
So: player.log(1) = arg is player, arg2 is 1
