### ISSUE TITLE
Basic Rotation does not work with new Core

### ISSUE THREAD

**Issue by tw88** [MrTheSoulz/NerdPack#60]
local GUI = {  
    {type = "spinner", text = "test spinner", key = "test2", default = 95},  
    {type = "checkbox", text = "test checkbox", key = "test", default = false}  
}  

local function exeOnLoad()  
    -- ClallBacks  
end  

local inCombat = {
	{'12294'}, 							-- Mortal-strike
}  

local outCombat = {  
}

NeP.Engine.registerRotation(71, 'Gosu-CR-Arms-Warrior', inCombat, outCombat, exeOnLoad, GUI)

These few lines do not work with the new Core.

**Comment by MrTheSoulz** [comment]
Wich unlocker? EWT?

**Comment by tw88** [comment]
Firehack

**Comment by MrTheSoulz** [comment]
Should be fixed, thanks!

**Comment by tw88** [comment]
as mentioned in disqord the rotation still gets stuck on detecting Battle Cry. It just keeps showing Battle Cry as next spell and gets stuck.

**Comment by MrTheSoulz** [comment]
Update and see if that still happens please.
